#!/usr/bin/env bash

set -euo pipefail

# this script patches files generated by shadcn CLI to fix import statements for compatibility
# with node subpath imports
#
# @see package.json for `postshadcn` that triggers this script after execution of `shadcn` script

# summary of the problem:
#
# current shadcn CLI generates import paths as follows:
#
# `import { cn } from '#/lib/utils'`
#
# this script corrects the import by removing the '/' that follows the '#':
#
# `import { cn } from '#lib/utils'`
#
# the fix enables type checking via `tsc --noEmit` that the shadcn CLI would otherwise break for the workspace.
#
# this situation could be avoided if shadcn CLI were to adopt a simple and declarative config format instead
# of implementing its own internal logic that accepts inputs from multiple sources.

PACKAGE_SRC_DIR="packages/react-ui/src"

WORKSPACE_ROOT="$(git rev-parse --show-toplevel)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# use git to return a list of files that are changed/staged/untracked and grep to isolate this package
modified_files=$(git ls-files --others --modified --exclude-standard | grep "^$PACKAGE_SRC_DIR/")

echo "Running script to fix shadcn cli's habit of borking node subpath imports..."

# loop over the modified files and process with `sed` to fix the import paths for valid node subpath imports
for file in $modified_files; do
  echo "> processing file: $file"

  # using sed with this `-i` backup file syntax is compatible with both GNU (linux) and BSD (MacOS) variants
  # the regex captures the quotes as well so it supports both single and double quote preferences
  sed -i.bak -E "s|^\s*import\s+(.*)\s+from\s+(['\"])#/(.*)\2|import \1 from \2#\3\2|" "$WORKSPACE_ROOT/$file"

  # compare the backup and potentially modified files and report if a change was made
  if ! cmp --silent "$WORKSPACE_ROOT/$file" "$WORKSPACE_ROOT/$file.bak"; then
    echo "> modified file: $file"
  fi

  rm "$WORKSPACE_ROOT/$file.bak"
done

echo "Script complete.\n"
