import { Link } from 'react-router'
import { PageLayout } from '@workspace/react-layout/page.layout'

export default function AboutPage(): JSX.Element {
  return (
    <PageLayout className="prose">
      <h1>About</h1>
      <p>
        This project template was created by <Link to="https://firxworx.com/">@firxworx</Link> (
        <Link to="https://github.com/firxworx">GitHub</Link>) in TypeScript and powered by{' '}
        <Link to="https://vite.dev/">Vite</Link>.
      </p>
      <p>
        It includes <Link to="https://ui.shadcn.com/docs">shadcn/ui</Link> and CLI,{' '}
        <Link to="https://www.radix-ui.com/">radix-ui</Link>,{' '}
        <Link to="https://tailwindcss.com/docs/installation">tailwindcss</Link>, and the{' '}
        <Link to="https://fluid.tw/">fluid-tailwind plugin</Link>.
      </p>
      <p>
        A starter <Link to="https://react.dev/">React</Link> application with{' '}
        <Link to="https://reactrouter.com/en/main">react-router</Link> demonstrates how everything in the workspace fits
        together.
      </p>
      <p>
        The codebase is organized as a <Link to="https://pnpm.io/workspaces">pnpm workspace</Link> (monorepo) with
        internal packages (libraries) housing shared react components, <Link to="https://zod.dev/">zod</Link> schemas,
        types, and <Link to="https://tailwindcss.com/docs/presets">tailwind presets</Link> that can be used in multiple
        projects across the workspace.
      </p>
      <p>
        There are two tailwind presets: <code>tw-preset-shadcn</code> effectively "installs" shadcn/ui and{' '}
        <code>tw-preset-workspace</code> defines the tailwind theme and customizations.
      </p>
      <p>
        Performant linting and formatting is powered by <Link to="https://biomejs.dev/">biome</Link>.
      </p>
      <p>
        A preview is deployed on <Link to="https://developers.cloudflare.com/pages/">Cloudflare Pages</Link>:
      </p>
      <div className="~p-4/6 rounded-md bg-muted border max-w-fit">
        <Link to="https://vite-shadcn-workspace.pages.dev">https://vite-shadcn-workspace.pages.dev</Link>
      </div>
      <p>View the code on GitHub:</p>
      <div className="~p-4/6 rounded-md bg-muted border max-w-fit">
        <Link to="https://github.com/firxworx/vite-shadcn-workspace">
          https://github.com/firxworx/vite-shadcn-workspace
        </Link>
      </div>
      <h2>Acknowledgements</h2>
      <h3>Design</h3>
      <p>
        The landing page design and components are loosely based on the boilerplate generated by the{' '}
        <Link to="https://kirimase.dev/">Kirimase CLI</Link> created by{' '}
        <Link to="https://www.nicoalbanese.com/">Nico Albanese</Link>.
      </p>
      <h3>Illustrations</h3>
      <p>
        The vector illustrations on the landing page are thanks to <Link to="https://popsy.co/">popsy.co</Link>.
      </p>
      <h3>Icons</h3>
      <p>
        Icons from <Link to="https://lucide.dev/">Lucide</Link> are distributed under its{' '}
        <Link to="https://lucide.dev/license">ISC License</Link>.
      </p>
      <p>
        The ownership of trademarks related to brands such as the GitHub logo or leading social media platforms belongs
        to their respective copyright holders. Icons related to these brands are distributed under fair-use.
      </p>

      <h2>License</h2>
      <p>
        Code is licensed under MIT by <Link to="https://firxworx.com/">Kevin Firko</Link> &{' '}
        <Link to="https://bitcurve.com/">Bitcurve</Link>.
      </p>
    </PageLayout>
  )
}
